[alias]
it = "test --test integration_test -F puppet-integration-tests -- --test-threads 1 --nocapture"
it-release = "test --release --test integration_test -F puppet-integration-tests -- --test-threads 1 --nocapture"