name: Main

on:
  push:
    branches: [ main ]
    tags: [ "[0-9]+.[0-9]+.[0-9]+*" ]
  #pull_request:
  #  branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  extract_changelog:
    name: Extract changelog
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2

    - name: Extract changelog
      shell: bash
      continue-on-error: true  # If parsing the changelog fails, continue with empty changelog
      run: |
        cargo install --verbose --version 0.4.7 parse-changelog
        export VERSION="$GITHUB_REF_NAME"
        parse-changelog CHANGELOG.md "$VERSION" > release-changelog.md
    
    - uses: actions/upload-artifact@v4
      with:
        name: release-changelog
        path: release-changelog.md

  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Prepare environment
      uses: ./.github/actions/wden-rust-env-setup
    
    - name: Run tests
      run: cargo test --verbose --release
    - name: Run integration tests
      if: runner.os == 'Linux'
      run: cargo --verbose it-release

    - name: Build
      run: cargo build --verbose --release
    
    - name: Copy binaries to out dir with target name
      shell: bash
      run: |
        mkdir -p out/
        target_triple="$(rustc -vV | sed -n 's|host: ||p')"
        if [ "${{ matrix.os }}" = "windows-2022" ]; then
          cp target/release/wden.exe "out/wden-${target_triple}.exe"
        elif [ "${{ matrix.os }}" = "ubuntu-22.04" ]; then
          cp target/release/wden "out/wden-${target_triple}"
        fi

    - uses: actions/upload-artifact@v4
      with:
        name: wden-bin-${{ matrix.os }}
        path: out/

  publish_release:
    name: Publish release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    needs: [extract_changelog, build]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v6
      with:
        merge-multiple: true
        path: artifacts/
    - name: list artifacts
      shell: bash
      run: ls -laR artifacts/
    - uses: softprops/action-gh-release@v2
      with:     
        body_path: artifacts/release-changelog.md
        body: ''  # Empty string as fallback
        files: |
          LICENSE
          artifacts/wden-*